# Specify path to conda env
conda_env: '../../env'

# Specify path to a tab-separated sampletable, consisting of 
# the following columns:
# - samplename: unique sample identifier
# - input_vsi: path to a vsi file
sampletable: 'config/sampletable.txt'

# Output directory
outdir: '../../images/converted'

# Specify the series to be converted. 
# NOTE: 
# - Determine the series based on the input metadata. 
# - Select one for multi-channel with a desired resolution
# - If `None`, python specifies one series with the highest resolution
#   and multi-channel data
ser: None

# Set to `True` if you want to save as pyramidal output
# See https://www.microscopesinternational.com/support/kb/article/ngn1076.aspx
pyramidal: True

